### ISSUE TITLE
Error encountered when Dequeue message from redis cluster

### ISSUE THREAD

**Issue by edwardmeng** [FoundatioFx/Foundatio.Redis#9]
'''
[19:23:37 ERR] Retry error: Key has MOVED from Endpoint 10.20.0.14:9001 and hashslot 9229 but CommandFlags.NoRedirect was specified - redirect not followed for RPOPLPUSH {q:gaiaworks1-MailMessage}:in. IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=32767,Min=4,Max=32767), Local-CPU: n/a
StackExchange.Redis.RedisServerException: Key has MOVED from Endpoint 10.20.0.14:9001 and hashslot 9229 but CommandFlags.NoRedirect was specified - redirect not followed for RPOPLPUSH {q:gaiaworks1-MailMessage}:in. IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=0,Free=32767,Min=4,Max=32767), Local-CPU: n/a
   at Foundatio.Queues.RedisQueue`1.<DequeueIdAsync>b__56_0() in C:\projects\foundatio-redis\src\Foundatio.Redis\Queues\RedisQueue.cs:line 331
   at Foundatio.Utility.Run.WithRetriesAsync[T](Func`1 action, Int32 maxAttempts, Nullable`1 retryInterval, CancellationToken cancellationToken, ILogger logger) in /app/src/Foundatio/Utility/Run.cs:line 41
'''

**Comment by ejsmith** [comment]
You are running it in a cluster? There are going to be a bunch of issues like this that you run into with a Redis Cluster.

**Comment by Telavian** [comment]
I am testing this and I think it is great however I am confused about the comment.
Is this not designed to work when redis is clustered?
What needs to change in order for it to work?
Is this even realistic?

**Comment by niemyjski** [comment]
There are some operations that we are doing that use scripting that doesn't work in the cluster mode. That said we should fully support running in sentinel. You'd need to run all the tests against a cluster to see everything that would need to be changed for clusters.
